---
title: "Projections and Basis Functions with Chemistry"
author:
  - name: David Jordan
    url: mailto:public@livingphysics.org
date: "2025-02-19"
categories: ["Observable Functions", "Projection Operators"]
code-fold: true
draft: false
feed:
  image-height: 60
  image-width: 60
---
This is a short note which connects how well chosen changes to the chemical kinetics in a simple system can manifest mathematically as either altering the projections onto a constant set of basis functions, or altering the basis functions while maintaining the projection. This note is intended to provide a very basic foundation for a more sophisticated model of learning and evolution in physical/chemical systems.

Given a simple chemical reaction 

$$
\Large
\ce{a<=>[{\lambda}][{\nu}]b}
$$

Recall from the previous note the simple conversion reaction with dynamics given by: $$\frac{d}{dt}\begin{bmatrix}a\\b\end{bmatrix} = \begin{bmatrix}-\lambda & \nu \\ \lambda & -\nu\end{bmatrix}\begin{bmatrix}a\\b\end{bmatrix}$$

Some of the formulas I presented without derivation in the previous notes were derived from looking at the  eigen-decomposition of the Laplacian.
$$\large  L = UDU^{-1} $$
This gives us the eigenvector matrix $$ U = \begin{bmatrix} \frac{\nu}{\lambda} & -1 \\ 1 & 1 \end{bmatrix}, D = \begin{bmatrix} 0 & 0 \\ 0 & -(\nu+\lambda) \end{bmatrix} $$
We can use this transformation to define new set of *uncoupled* coordinates 
$$\large \begin{align}\dot{\vec{x}} = L\vec{x} &= UDU^{-1}\vec{x} \\\dot{\vec{x}}&= UDU^{-1}\vec{x} \\  U^{-1}\dot{\vec{x}}&=  DU^{-1}\vec{x}\end{align}$$If we define $z=U^{-1}x$ then we now have a dynamical system of 2 variables that do not interact (compare to the original $a,b$ sytem which has interactions)
$$\large \frac{d\vec{z}}{dt} = Dz = \begin{bmatrix} 0 & 0 \\ 0 & -(\nu+\lambda) \end{bmatrix}z$$
Thus:
$$
\begin{align} dz_1/dt &= 0 \\ dz_2/dt &= -(\nu+\lambda)z_2 \end{align}
$$
which gives
$$ \Large
\begin{align} z_1(t) &= z_1(0) \\ z_2(t) &= z_2(0)e^{-(\nu+\lambda)t}\end{align}
$$
Noting that $z_1 = \frac{\lambda}{\lambda+\nu}a+\frac{\lambda}{\lambda+\nu}b$ and $z_2 = \frac{-\lambda}{\lambda+\nu}a+\frac{\nu}{\lambda+\nu}b$, which is how I derived the observable function $c$ in the note [Introduction and Motivations for a Projection Operator Approach](../proj_operator/proj_operator.qmd).  $z_1$ represents the total (probability) mass and $\dot{z_1}=0$ reflects conservation of (probability) mass. 

We've carried out this eigen-decomposition because the natural dynamics of $a$ ad $b$ can be represented as a linear combination of the uncoupled dynamics of $z_1$ and $z_2$.  In the language I have been developing in the last few notes, I would say that $z_1(t)$ and $z_2(t)$ are the basis functions and the dynamics of $a$ and $b$ are projections onto these basis functions.  

It is clear in this simple example that the basis functions are defined by the eigenvalues and the projection is defined by the eigenvectors.  Thus if we change the eigenvalues without changing the eigenvectors we adjust the basis functions and if we change the eigenvectors while keeping constant eigenvalues we change the projection. 

Lets now consider the action of an enzyme which lowers the activation energy barrier for the reaction.  This results in a proportional increase in both $\nu$ and $\lambda$
$$
\large
\ce{a<=>[{r\lambda}][{r\nu}]b}
$$
The eigenvector associated with the 0 eigenvalue is then $\frac{r\nu}{r\lambda} = \frac{\nu}{\lambda}$, and is thus unchanged. However, the non-zero eigenvalue is now $-(r\nu+r\lambda)=-r(\nu+\lambda)$.  This results in the second basis function changing to $$ \large z_2(t) = z_2(0)e^{-r(\nu+\lambda)t}$$Because the dynamics of $a$ and $b$ are linear combinations of $z_1$ and $z_2$ and the dynamics of $z_2$ are now much faster (by a factor of $r$) the resulting dynamics of a and b will be faster, but the resulting steady state concentrations of $a$ and $b$ will be unchanged.  This matches our intuition based on activation energy changes in equilibrium systems. 

Alternatively, in this simple system, we can adjust the projections without changing the basis functions.  We do this by adjusting $\nu$ and $\lambda$ such that their sum stays constant.  This corresponds to a process which maintains the *total flux* in the system but adjusts the flux balance[^1] (this necessarily corresponds to binding energy differences here). $$\begin{align} \lambda \to (\lambda + r) \\ \nu\to(\nu-r)\end{align}$$This changes the steady state ratio of $a$ and $b$ but leaves the kinetics unchanged.  This is because the basis functions are unchanged: $$ \large z_2(t) = z_2(0)e^{-(\nu+r+\lambda-r)t} = z_2(0)e^{-(\nu+\lambda)t}$$This uncoupling of the dynamics into independent observable functions $z$ is always possible for Laplacian dynamics.  To connect it to some of the concepts introduced in previous notes, we can think of the functions $z$ as observable functions of the *natural coordinates* $a$ and $b$, where each observable function has dynamics that are closed on its own 1D subspace (this is a restatement of the uncoupling condition).  We can also think of the dynamics of $a$ and $b$ as being projections onto the basis functions defined by $z$.  Interestingly the basis functions $z$ define a spectrum of time-scales for the dynamics because the dynamics of the molecular concentrations will be linear combinations of the basis functions defined by the eigenvalue spectrum.  In the next note I will explore how these notions can be applied to larger networks, and look at some connections to kinetic regime vs energetic regime proofreading, building finally to connections to orthogonality. 

[^1]:This possibly implies the existence of a basic chemical reaction modification (like an enzyme) that shifts the flux balance of a reaction while preserving the total reaction flux.  I could not think of a ready biological example of such a thing, but I would keep an eye out for something that fits this.