---
title: "Observable functions and their dynamics"
author:
  - name: David Jordan
    url: mailto:public@livingphysics.org
date: "2024-06-24"
categories: ["Observable Functions", "Projection Operators"]
code-fold: true
draft: false
feed:
  image-height: 60
  image-width: 60
---
In the previous note I concluded with these points about observable functions and projection, 

> 1) *Observable functions* are sets of functions of underlying state variables.  

> 2) These sets can be much smaller than the underlying dynamical system of which they are functions.  This leads to *concentration of dimension* and can be formalized as a projection operator.

> 3) Closed observable subspaces are sets of observable functions whose dynamics are (approximately) self determined, that is that they can be expressed as functions of the observables themselves. 

At this point I hope you are comfortable with the concentration of dimension via function projection, in this note, I want to explore the expansion of dimension by observable functions. The main reason we would expand dimensionality is that it can make some computations easier, and that it can *linearize* a non-linear dynamical system. Consider the following example[^1]

$$ \Large \begin{align} \dot{x_1} &= \mu x_1 \\ \dot{x_2} &= \lambda(x_2-x_1^2) \end{align}
$$
This is a 2D non-linear dynamical system because of the $x_1^2$ term.  Lets propose a set of observable functions $y_i$ with the goal of linearizing the system.

$$ \begin{bmatrix} y_1\\y_2\\y_3\end{bmatrix} = \begin{bmatrix} x_1\\x_2\\x_1^2\end{bmatrix} $$
Now lets look at the dynamics of $y$

$$ \Large \begin{align} \dot{y_1} &= \mu x_1 = \mu y_1 \\ \dot{y_2} &= \lambda(x_2-x_1^2) = \lambda(y_2-y_3)\\ \dot{y_3} &= 2x_1\dot{x_1}\\ &= 2y_1(\mu y_1) \\ &=2\mu y_3 \end{align}
$$

giving,
$$\large \frac{d}{dt}\begin{bmatrix} y_1\\y_2\\y_3\end{bmatrix}=\begin{bmatrix} \mu&0&0 \\ 0 & \lambda & -\lambda \\ 0 & 0 & 2\mu\end{bmatrix} \begin{bmatrix} y_1\\y_2\\y_3\end{bmatrix}$$
The observable functions for this particular system also have the closure property I mentioned in the last note.  We have expanded the dimensionality of the system, but the new system of observable functions has dynamics which are only functions the the $y_i$ themselves.  This need not be the case.  For example, lets look at the example of the following 1D nonlinear dynamics. 
$$\Large \dot{x_1} = -\nu x_1^2 + (\lambda-\nu)x_1 + \lambda$$
If we try the same trick here, 
$$ \begin{bmatrix} y_1\\y_2\end{bmatrix} = \begin{bmatrix} x_1\\x_1^2\end{bmatrix} $$

We have 
$$ $$ $$\Large \begin{align} \dot{y_1} &= \dot{x_1} = -\nu y_2 + (\lambda-\nu)y_1 + \lambda \\ \dot{y_2} &= 2x_1\dot{x_1} = 2y_1(-\nu y_2 + (\lambda-\nu)y_1 + \lambda)\\ &= -2\nu y_1y_2+2(\lambda-\nu)y_y+2\lambda y_1 \\ \end{align}$$
Unfortunately here we see a problem, $y_1y_2$ is not a linear function of our set of observables.  $y_1y_2 = x_1^3$, so we would need to add this to our observable functions, 
$$ \begin{bmatrix} y_1\\y_2\\y_3\end{bmatrix} = \begin{bmatrix} x_1\\x_1^2\\x_1^3\end{bmatrix} $$
with $$ \Large \begin{align} \dot{y_3} &= 3x_1^2\dot{x_1} = 3y_2(-\nu y_2 + (\lambda-\nu)y_1 + \lambda) \\ &= -3\nu y_2^2+3(\lambda-\nu)y_1y_2 +3\lambda y_2 \\ &= -3\nu y_2^2+3(\lambda-\nu)y_3 +3\lambda y_2 \end{align}$$
Again we have a term that is not in our current observable set $y_2^2 = x^4$.  We can however continue this process for an infinite number of terms, if we introduce $y_0$ to account for the constant term, we can write these dynamics with a matrix of the form:

$$\Large \frac{d\vec{y}}{dt} = \begin{bmatrix} 0&0&0&0&0&...&0\\ \lambda & \lambda-\nu & -\nu & 0& 0&... & 0 \\ 0 & 2\lambda & 2(\lambda-\nu) & -2\nu & 0 &...&0 \\ 0 & 0& 3\lambda & 3(\lambda-\nu) & -3\nu &...&0 \\ ...&&&&&&...\end{bmatrix} \vec{y}$$
So we have in infinite dimensional linear operator which has the same dynamics as our non-linear system.  In fact, we are guaranteed to always be able find such an infinite dimensional linear operator[^2]

Why is this useful though? We have traded non-linear dynamics for infinite dimensional linear dynamics.  Other than control theory applications, its not clear why linear dynamics are important, and also, any real control system is finite dimensional.  At this point the connection to orthogonality is hopefully emerging.  The Laplacian dynamics from our master equation formulation is a linear operator.  It is finite dimensional, but we saw in the last note how we can concentration dimension with projection operators.  We can do this as well with the infinite dimensional operators like the one above.  The Galerkin projection, that is the one that simply ignores most of the dimensions, is easiest, but like the example in the previous note, if the subspace onto which you are projecting is not closed, the dynamics floats off over time.  In other words, the projection does not exactly recapitulate the dynamics, but rather is an approximation.  Can chemical reaction networks use their Laplacian dynamics as such an approximation? The questions that I will try to answer in the next few notes are 

1) Can a chemical reaction network can use its dynamics as a finite dimensional linear approximation of an arbitrary dynamical system.
2) If so, what are the "natural basis functions" of Laplacian dynamics
3) How  does a physical system use thermodynamics to perform these operations without a notion of explicitly approximating the non-linear dynamics. 

As a teaser, lets go back to the one dimensional dynamical system that we needed an infinite expansion to represent.  
$$\Large \dot{x_1} = -\nu x_1^2 + (\lambda-\nu)x_1 + \lambda$$
With our naive choice of observable functions, we saw that we needed an infinite dimensional dynamical linear dynamics to represent it in that set of observables.  In fact any finite Galerkin projection in that basis is a pretty bad approximation, but what if we are more clever with the basis functions we select.  The form of this equation is written in this way for a reason.  Lets go back to the simple chemical reaction network from the previous note 
$$
\Large
\ce{a<=>[{\lambda}][{\nu}]b}
$$
with its linear dynamics
$$\frac{d}{dt}\begin{bmatrix}a\\b\end{bmatrix} = \begin{bmatrix}-\lambda & \nu \\ \lambda & -\nu\end{bmatrix}\begin{bmatrix}a\\b\end{bmatrix}$$
If I choose an observable function of this dynamics to be the ratio of the two species 
$$\Large x_1 = \frac{b}{a}$$
then the dynamics of $x_1$ are given by 
$$\Large \begin{align} \dot{x_1} &= \frac{\dot{b}a-\dot{a}b}{a^2} \\ &= \frac{(\lambda a-\nu b)a - (-\lambda a + \nu b)b}{a^2} \\ &= \frac{\lambda a^2 - \nu a b +\lambda a b -\nu b^2}{a^2} \\ &= -\nu\frac{b^2}{a^2}+(\lambda-\nu)\frac{ab}{a^2}+\lambda\frac{a^2}{a^2}\\&= -\nu x_1^2+(\lambda-\nu)x_1+\lambda \end{align}$$
So it turns out that the dynamics of this non-linear system can in fact be recapitulated by a closed linear system, generated by a Laplacian chemical reaction network.  If our observable function is the ratio of two species. 

At this point I hope you feel comfortable. 
1) Reducing dimensionality with projection operators. Sometimes this projection can be exactly preserving for closed, invariant subspaces. Otherwise its an approximation
2) Expanding dimensionality through the use of observable functions.  Sometimes we need to expand infinitely to get linear dynamics. But linear dynamics may not be the appropriate end goal.  Ultimately I'm interested in observable dynamics that can be recapitulated with observables realizable by chemical reaction networks.  These may be linear, Linearity is nice for our Laplacian dynamics, but even these are approximations based on time scale separation[^3]
3) Although I didn't explain it in detail in the last note (I will in a companion note) The transformation I used to find a closed projection was based on the eigen-decomposition of the linear dynamics given by $\frac{d}{dt}\begin{bmatrix}a\\b\end{bmatrix} = \begin{bmatrix}-\lambda & \nu \\ \lambda & -\nu\end{bmatrix}\begin{bmatrix}a\\b\end{bmatrix}$.  This is another nice property of linearized dynamics, we can find eigenfunctions which have characteristic time scales and which are uncoupled (if this is unclear stay tuned for the next note).  These eigen-decompositions as dimension preserving rotations of the dynamics.

So now we can take dynamical systems, expand their dimensionality, contract their dimensionality, and rotate their representations at will.  The math here is not new or that difficult, but the new part (I hope) will be in seeing how chemical reaction networks can do this using only *local* information in a self organized way.

[^1]: Brunton SL, Brunton BW, Proctor JL & Kutz JN (2016) Koopman Invariant Subspaces and Finite Linear Representations of Nonlinear Dynamical Systems for Control. _PLoS One_ 11: e0150171
[^2]: Koopman BO (1931) Hamiltonian Systems and Transformation in Hilbert Space. _Proc Natl Acad Sci U S A_ 17: 315–318
[^3]: Mirzaev I & Gunawardena J (2013) Laplacian dynamics on general graphs. _Bull Math Biol_ 75: 2118–2149